version: '3.4'

services:
  leakzon.webapi:
    image: ${DOCKER_REGISTRY-}leakzonwebapi
    build:
      context: .
      dockerfile: Leakzon.WebApi/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    # volumes:
    #   - mongodb_data:/data/db